name: Rust CI

on:
  push:
    branches: [ "fix-gha" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  LIBTORCH_VERSION: 2.7.1
  LIBTORCH_CXX11_ABI: 1

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy, rust-src

      - name: Verify Rust installation
        run: |
          rustc --version
          cargo --version
          rustup show

      - name: Cache cargo registry
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip build-essential cmake pkg-config

      - name: Download and install libtorch
        run: |
          cd /tmp
          wget https://download.pytorch.org/libtorch/cpu/libtorch-cxx11-abi-shared-with-deps-${LIBTORCH_VERSION}%2Bcpu.zip
          unzip libtorch-cxx11-abi-shared-with-deps-${LIBTORCH_VERSION}+cpu.zip
          sudo mv libtorch /usr/local/
          echo "LIBTORCH=/usr/local/libtorch" >> $GITHUB_ENV
          echo "LD_LIBRARY_PATH=/usr/local/libtorch/lib:$LD_LIBRARY_PATH" >> $GITHUB_ENV

      - name: Verify libtorch installation
        run: |
          ls -la /usr/local/libtorch/
          ls -la /usr/local/libtorch/lib/

      - name: Clean cargo cache (if needed)
        run: |
          cargo clean

      - name: Update cargo index
        run: cargo update

      - name: Check Cargo.toml
        run: |
          echo "Checking Cargo.toml for potential issues..."
          cat Cargo.toml

      - name: Build with verbose output
        run: cargo build --verbose
        env:
          LIBTORCH: /usr/local/libtorch
          LD_LIBRARY_PATH: /usr/local/libtorch/lib
          LIBTORCH_BYPASS_VERSION_CHECK: 1
          RUST_BACKTRACE: 1

      - name: Run tests
        run: cargo test --verbose
        env:
          LIBTORCH: /usr/local/libtorch
          LD_LIBRARY_PATH: /usr/local/libtorch/lib
          LIBTORCH_BYPASS_VERSION_CHECK: 1
          RUST_BACKTRACE: 1