name: Rust CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  LIBTORCH_VERSION: 2.7.1
  LIBTORCH_CXX11_ABI: 1

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Cache cargo registry
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip build-essential cmake

      - name: Download and install libtorch
        run: |
          cd /tmp
          wget https://download.pytorch.org/libtorch/cpu/libtorch-cxx11-abi-shared-with-deps-${LIBTORCH_VERSION}%2Bcpu.zip
          unzip libtorch-cxx11-abi-shared-with-deps-${LIBTORCH_VERSION}+cpu.zip
          sudo mv libtorch /usr/local/
          echo "LIBTORCH=/usr/local/libtorch" >> $GITHUB_ENV
          echo "LD_LIBRARY_PATH=/usr/local/libtorch/lib:$LD_LIBRARY_PATH" >> $GITHUB_ENV

      - name: Verify libtorch installation
        run: |
          ls -la /usr/local/libtorch/
          ls -la /usr/local/libtorch/lib/

      - name: Build
        run: cargo build --verbose
        env:
          LIBTORCH: /usr/local/libtorch
          LD_LIBRARY_PATH: /usr/local/libtorch/lib
          LIBTORCH_BYPASS_VERSION_CHECK: 1

      - name: Run tests
        run: cargo test --verbose
        env:
          LIBTORCH: /usr/local/libtorch
          LD_LIBRARY_PATH: /usr/local/libtorch/lib
          LIBTORCH_BYPASS_VERSION_CHECK: 1